import { MidnightBech32m } from '@midnight-ntwrk/wallet-sdk-address-format';
import * as rx from 'rxjs';
import { loadConfig } from './config.js';
import { startRelayerWallet } from './wallet.js';

/**
 * Registers a wallet's NIGHT UTXOs for passive DUST generation.
 *
 *     npm run relayer:dust                     # the relayer's own wallet
 *     npm run deploy:preview:operator-dust     # the deploy's operator wallet
 *
 * NIGHT alone cannot pay a fee. DUST is what pays, and DUST is generated by
 * NIGHT that has been registered for it. A relayer holding NIGHT but not
 * registered will fail every vote at the fee step, which is the failure this
 * script exists to prevent.
 *
 * Only the owner of the UTXOs can register them — the signature comes from that
 * wallet's own unshielded keystore — so no wallet can do this on another's
 * behalf. That is why the operator wallet needs its own run rather than being
 * covered by the relayer's; see resolveConfig() below. The registration
 * transaction is finalized and submitted without a balancing step, which is
 * what breaks the chicken-and-egg of needing DUST in order to obtain DUST.
 */
const config = resolveConfig();
console.log(`network: ${config.networkId}`);
console.log(`wallet:  ${config.label}`);
console.log('starting wallet and syncing (a wallet that starts with nothing needs over an hour)…');

const wallet = await startRelayerWallet(config);

/** Minutes to wait for the funding UTXO to appear before giving up. */
const WAIT_FOR_NIGHT_MS = 8 * 60 * 1000;

/** DUST accrues only after a full replay, so this bound is generous. */
const DUST_WAIT_MS = 35 * 60 * 1000;

/**
 * A cold wallet replays the whole indexer history. On Preview that was about
 * 27 minutes in September 2026 and about 85 in October, more on a busy
 * machine. The 45-minute bound this had would now stop a wallet that is fine.
 */
const SYNC_WAIT_MS = 3 * 60 * 60 * 1000;

/**
 * Bounds a wallet call and narrates it.
 *
 * These SDK calls carry no timeout of their own. When the node's RPC socket
 * closes mid-call — which Preview does routinely — the promise can simply never
 * settle, and the script sits silent with no way to tell a slow estimate from a
 * dead connection. A bounded, labelled step turns that into a failure that says
 * which call stopped responding.
 */
async function step<T>(label: string, minutes: number, work: () => Promise<T>): Promise<T> {
  console.log(`${label}…`);
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      work(),
      new Promise<never>((_, reject) => {
        timer = setTimeout(
          () => reject(new Error(`${label} did not return within ${minutes} minutes.`)),
          minutes * 60 * 1000,
        );
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

/**
 * Progress for the long waits, so the terminal is never dead.
 *
 * Prints the replay cursors, not just a boolean. `synced=false` on its own
 * cannot distinguish a wallet that is making steady progress from one that
 * stalled after a dropped connection — which is exactly the ambiguity that led
 * to a healthy run being killed on 2 September.
 */
let lastDustLog = 0;
function narrateDustWait(state: WalletStateForNarration): void {
  const now = Date.now();
  if (now - lastDustLog < 30_000) return;
  lastDustLog = now;
  const cursor = (section: SyncProgressish | undefined): string => {
    const applied = section?.progress?.appliedIndex;
    const total = section?.progress?.highestRelevantWalletIndex;
    if (applied === undefined || total === undefined) return '?';
    const a = Number(applied);
    const t = Number(total);
    return t > 0 ? `${a}/${t} (${((100 * a) / t).toFixed(1)}%)` : `${a}`;
  };
  console.log(
    `  waiting… synced=${state.isSynced} dust=${state.dust.availableCoins.length} ` +
      `shielded=${cursor(state.shielded)} dustSync=${cursor(state.dust)}`,
  );
}

interface SyncProgressish {
  readonly progress?: {
    readonly appliedIndex?: bigint | number | string;
    readonly highestRelevantWalletIndex?: bigint | number | string;
  };
}

interface WalletStateForNarration {
  readonly isSynced: boolean;
  readonly shielded?: SyncProgressish;
  readonly dust: SyncProgressish & { readonly availableCoins: readonly unknown[] };
}

try {
  // Print the address before any submission. This script signs with whichever
  // seed it was given, so an operator must be able to see which wallet is
  // about to be changed while there is still time to abort.
  const first = await rx.firstValueFrom(wallet.facade.state());
  console.log(
    `registering for: ${MidnightBech32m.encode(config.networkId, first.unshielded.address as never).asString()}`,
  );

  // Fail fast on the common mistake — an unfunded wallet — without paying for a
  // full replay first. This only decides whether there is anything to do; the
  // registration itself needs a fully synced dust wallet and waits for one
  // below. Narrate progress so the terminal is never dead.
  let latest: Awaited<ReturnType<typeof wallet.facade.waitForSyncedState>> | null = null;
  let lastLog = 0;

  const state = await rx
    .firstValueFrom(
      wallet.facade.state().pipe(
        rx.tap((s) => {
          latest = s;
          const now = Date.now();
          if (now - lastLog > 10_000) {
            lastLog = now;
            console.log(
              `  syncing… synced=${s.isSynced} night=${s.unshielded.availableCoins.length} dust=${s.dust.availableCoins.length}`,
            );
          }
        }),
        rx.filter((s) => s.unshielded.availableCoins.length > 0),
        rx.timeout({ first: WAIT_FOR_NIGHT_MS, each: WAIT_FOR_NIGHT_MS }),
      ),
    )
    .catch(() => latest);

  if (!state) {
    console.error('\nThe wallet produced no state at all. Check the indexer URL in relayer/.env.');
    process.exit(1);
  }

  // `state` here is an early snapshot: it was captured the moment NIGHT first
  // appeared, minutes before the replay finished. It is fine for deciding
  // whether this wallet is worth registering at all, but the UTXO objects in
  // it must NOT be the ones handed to the SDK — booking happens against the
  // fully replayed state, and stale UTXOs fail there with Wallet.SpendUtxo.
  // A fresh read replaces these once the sync completes.
  let current = state;
  let nightCoins = current.unshielded.availableCoins;
  const alreadyRegistered = nightCoins.filter((coin) => coin.meta.registeredForDustGeneration);
  let unregistered = nightCoins.filter((coin) => !coin.meta.registeredForDustGeneration);

  console.log(`NIGHT UTXOs: ${nightCoins.length} (registered: ${alreadyRegistered.length})`);
  console.log(`current DUST: ${state.dust.balance(new Date()).toString()}`);

  if (nightCoins.length === 0) {
    console.error(
      '\nThis wallet holds no NIGHT. Fund the unshielded address printed by\n' +
        '`npm run relayer:address` first, wait for it to confirm, then rerun.',
    );
    process.exitCode = 1;
  } else if (unregistered.length === 0) {
    console.log('\nEvery NIGHT UTXO is already registered. Nothing to do.');
  } else {
    // estimateRegistration() calls dust.waitForSyncedState() internally, so it
    // cannot return until the whole indexer history has been replayed — about
    // 27 minutes on Preview. Waiting here instead means the delay is visible and
    // attributable, rather than a silent SDK call that looks like a hang.
    if (!current.isSynced) {
      console.log('waiting for a full sync before registering…');
      const synced = await rx
        .firstValueFrom(
          wallet.facade.state().pipe(
            rx.tap((s) => narrateDustWait(s)),
            rx.filter((s) => s.isSynced),
            rx.timeout({ first: SYNC_WAIT_MS, each: SYNC_WAIT_MS }),
          ),
        )
        .catch(() => {
          throw new Error(
            `the wallet did not finish syncing within ${Math.round(SYNC_WAIT_MS / 60_000)} minutes; ` +
              'nothing was submitted, so it is safe to run this again',
          );
        });

      // Re-read from the synced state. The SDK books UTXOs against the wallet's
      // current availableUtxos map, keyed by `intentHash#outputNo`; handing it
      // objects from the pre-sync snapshot is what produced four consecutive
      // Wallet.SpendUtxo failures on 2 September.
      current = synced;
      nightCoins = current.unshielded.availableCoins;
      unregistered = nightCoins.filter((coin) => !coin.meta.registeredForDustGeneration);
      console.log(
        `synced. NIGHT UTXOs now: ${nightCoins.length} (unregistered: ${unregistered.length})`,
      );
      for (const coin of unregistered) {
        console.log(`  will register ${coin.utxo.intentHash}#${coin.utxo.outputNo}`);
      }
      if (unregistered.length === 0) {
        // Report what the caller actually needs to know. `deploy:preview` gates
        // on dust.availableCoins.length > 0 AND a positive balance, so a wallet
        // whose NIGHT is registered can still be unusable if generation has not
        // produced a coin yet. Saying only "nothing to register" hides that.
        const dustCoins = current.dust.availableCoins.length;
        const dustBalance = current.dust.balance(new Date());
        console.log('Every NIGHT UTXO is already registered. Nothing to register.');
        console.log(`DUST coins: ${dustCoins}`);
        console.log(`DUST balance: ${dustBalance.toString()}`);
        if (dustCoins === 0 || dustBalance <= 0n) {
          console.log('This wallet cannot pay fees yet. Registered NIGHT generates DUST over');
          console.log('time, so this resolves by waiting, not by registering again.');
          process.exitCode = 1;
        } else {
          console.log('This wallet can pay fees.');
        }
        process.exit(process.exitCode ?? 0);
      }
    }

    // The fee estimate is informational — it is logged and never used. It is
    // skipped by default because it is not free: it forces its own
    // waitForSyncedState(), and on 2 September a run that estimated first then
    // failed to book the very UTXO it had just inspected
    // (Wallet.SpendUtxo). Set DUST_FEE_ESTIMATE=true to observe the fee when
    // diagnosing; leave it off for a registration you actually want to land.
    if (process.env.DUST_FEE_ESTIMATE?.trim() === 'true') {
      const estimate = await step('estimating the registration fee', 10, () =>
        wallet.facade.estimateRegistration(unregistered),
      );
      console.log(`registration fee estimate: ${estimate.fee.toString()}`);
    }

    const recipe = await step(
      `building the registration for ${unregistered.length} UTXO(s)`,
      8,
      () =>
        wallet.facade.registerNightUtxosForDustGeneration(
          unregistered,
          wallet.unshieldedKeystore.getPublicKey(),
          (payload) => wallet.unshieldedKeystore.signData(payload),
        ),
    );
    const finalized = await step('finalizing', 8, () => wallet.facade.finalizeRecipe(recipe));
    const txId = await step('submitting', 8, () => wallet.facade.submitTransaction(finalized));
    console.log(`submitted: ${txId}`);

    // Past this point the registration is on chain. Anything that fails below
    // is a reporting failure, not a reason to register a second time.
    console.log('waiting for DUST to appear (needs a full sync; typically ~30 minutes)…');
    const after = await rx
      .firstValueFrom(
        wallet.facade.state().pipe(
          rx.tap((s) => narrateDustWait(s)),
          rx.filter((s) => s.isSynced),
          rx.filter((s) => s.dust.availableCoins.length > 0),
          rx.timeout({ first: DUST_WAIT_MS, each: DUST_WAIT_MS }),
        ),
      )
      .catch(() => null);

    if (!after) {
      console.log(
        `\nThe registration was submitted (${txId}) but DUST had not appeared within ` +
          `${Math.round(DUST_WAIT_MS / 60_000)} minutes.\n` +
          'It is on chain regardless — do NOT run this again. Confirm with\n' +
          '`RELAYER_STATUS_WAIT_MS=1740000 npm run relayer:status`.',
      );
      process.exitCode = 1;
    } else {
      console.log(`\nDUST coins: ${after.dust.availableCoins.length}`);
      console.log(`DUST balance: ${after.dust.balance(new Date()).toString()}`);
      console.log('\nThis wallet can now pay fees.');
    }
  }
} finally {
  await wallet.stop().catch(() => undefined);
}
process.exit(0);

/**
 * Resolves which wallet to register.
 *
 * By default this is the relayer's own wallet, read from `RELAYER_SEED`. The
 * deploy also needs a *second*, independent operator wallet
 * (`V2_OPERATOR_FEE_SEED_HEX`), and `deploy:preview` refuses to start until
 * that wallet reports DUST — but funding only ever grants NIGHT, and NIGHT
 * generates no DUST until its UTXOs are registered. Only the owner of those
 * UTXOs can register them, so the operator wallet cannot be served by the
 * relayer's seed.
 *
 * `DUST_REGISTER_SEED_HEX` points this script at that wallet instead. Prefer
 * it over editing `relayer/.env`: the deploy asserts that the v2 role secrets
 * are independent of the relayer seed, and a `.env` left pointing at the wrong
 * wallet is how two processes came to share one DUST coin and fail with
 * error 170.
 */
function resolveConfig() {
  const base = loadConfig();
  const override = process.env.DUST_REGISTER_SEED_HEX?.trim().toLowerCase().replace(/^0x/, '');
  if (!override) {
    return { ...base, label: "the relayer's own wallet (RELAYER_SEED)" };
  }
  if (!/^[0-9a-f]{64}$/.test(override)) {
    // Fail on shape alone; the value itself must never reach a log line.
    throw new Error('DUST_REGISTER_SEED_HEX must be 64 hexadecimal characters (32 bytes).');
  }
  return { ...base, seedHex: override, label: 'DUST_REGISTER_SEED_HEX' };
}
