/*
 * Words for the consultation brief. The English and French follow the Vote
 * Companion's reviewed wording where the two say the same thing.
 */
import type { CicoLocale } from '@/integration/locale';

const plural = (n: number, one: string, other: string) => (n === 1 ? one : other);

export const BRIEF_COPY = {
  en: {
    understand: 'Understand',
    ask: 'Ask',
    loading: 'Loading the brief…',
    unavailable: 'The brief could not be loaded.',
    retry: 'Try again',
    none: 'No brief is published for this consultation yet.',
    officialTitle: 'Official title',
    titleNote: 'Quoted word for word. We never rephrase it.',
    decided: 'What Parliament decided',
    nationalCouncil: (date: string | null) =>
      date ? `National Council, final vote of ${date}` : 'National Council, final vote',
    yes: 'Yes',
    no: 'No',
    abstained: 'Abstained',
    passage: 'The passage',
    meaningYes: 'A yes meant',
    meaningNo: 'A no meant',
    arguments: 'Arguments made in Parliament',
    argumentsNote: 'Each sentence opens the passage it comes from. The order is always the same.',
    forSide: 'For',
    againstSide: 'Against',
    inPreparation: 'Arguments in preparation',
    inPreparationBody:
      'They are published once a named person has reviewed them. The title and the counts above come from official records.',
    otherLanguage: (language: string) => `This brief is available in ${language}.`,
    coverThin: (passages: number, speakers: number) =>
      `The record covers this side thinly: ${passages} ${plural(passages, 'passage', 'passages')} from ${speakers} ${plural(speakers, 'speaker', 'speakers')}.`,
    coverOne: 'Only one member spoke for this side in the record.',
    coverSilent: 'No passage in the record argues this side. We do not fill the gap.',
    citeLabel: (n: number, speaker: string, date: string | null) =>
      `Source ${n}: ${speaker}${date ? `, ${date}` : ''}. Open the citation`,
    citation: (n: number) => `Source ${n}`,
    original: (language: string) => `Original · ${language}`,
    speaker: 'Speaker',
    role: 'Role',
    group: 'Group',
    chamber: 'Chamber',
    date: 'Date',
    openRecord: 'Open in the official record',
    watch: (start: string, end: string) => `Watch ${start}–${end}`,
    watchNote: 'The timing was set by a machine and not checked by a person.',
    close: 'Close',
    howMade: 'How this brief was made',
    howRule:
      'AI does the reading and the writing. Plain code decides what counts as evidence and attaches every source.',
    reviewed: (reviewer: string, date: string | null) =>
      date ? `Reviewed by ${reviewer} on ${date}` : `Reviewed by ${reviewer}`,
    model: 'Model',
    updated: 'Written',
    review: 'Human review',
    fullRecord: 'Read the full record',
    prepared: 'Prepared questions',
    preparedNote: 'Answered ahead of time from the record.',
    preparedPending: 'This answer is still being checked.',
    own: 'Your own question',
    placeholder: 'Ask what was said in Parliament about this',
    send: 'Ask',
    asking: 'Cleisthenes is reading the record…',
    privacy:
      'Your question is sent without your pass and without your name. Do not write personal details in it.',
    noAdvice: 'Cleisthenes explains what was said. It does not tell you how to answer.',
    signIn:
      'Own questions are not open to everyone yet. The prepared questions above need no account.',
    spent: 'No questions are left for now. Try again later.',
    failed: 'Cleisthenes could not answer. Try again.',
    unsourced: 'Cleisthenes found no sentence it could tie to a source.',
    limits: 'What this answer does not cover',
    limit: {
      'speech-not-decision': 'It reports what was said, not what was decided.',
      'text-coverage': 'The record we hold does not cover every session.',
      'machine-video-timing': 'Video timings were set by a machine.',
      withheld: 'Some sentences were withheld because no source supported them.',
    } as Record<string, string>,
  },
  es: {
    understand: 'Entender',
    ask: 'Preguntar',
    loading: 'Cargando la síntesis…',
    unavailable: 'No se pudo cargar la síntesis.',
    retry: 'Probar de nuevo',
    none: 'Todavía no hay una síntesis publicada para esta consulta.',
    officialTitle: 'Título oficial',
    titleNote: 'Citado palabra por palabra. Nunca lo reformulamos.',
    decided: 'Qué decidió el Parlamento',
    nationalCouncil: (date: string | null) =>
      date ? `Consejo Nacional, votación final del ${date}` : 'Consejo Nacional, votación final',
    yes: 'Sí',
    no: 'No',
    abstained: 'Abstenciones',
    passage: 'El pasaje',
    meaningYes: 'Un sí significaba',
    meaningNo: 'Un no significaba',
    arguments: 'Argumentos expuestos en el Parlamento',
    argumentsNote: 'Cada frase abre el pasaje del que proviene. El orden es siempre el mismo.',
    forSide: 'A favor',
    againstSide: 'En contra',
    inPreparation: 'Argumentos en preparación',
    inPreparationBody:
      'Se publican cuando una persona con nombre los revisó. El título y los números de arriba vienen de registros oficiales.',
    otherLanguage: (language: string) => `Esta síntesis está disponible en ${language}.`,
    coverThin: (passages: number, speakers: number) =>
      `El registro cubre poco esta posición: ${passages} ${plural(passages, 'pasaje', 'pasajes')} de ${speakers} ${plural(speakers, 'orador', 'oradores')}.`,
    coverOne: 'Solo una persona habló por esta posición en el registro.',
    coverSilent: 'Ningún pasaje del registro defiende esta posición. No llenamos ese vacío.',
    citeLabel: (n: number, speaker: string, date: string | null) =>
      `Fuente ${n}: ${speaker}${date ? `, ${date}` : ''}. Abrir la cita`,
    citation: (n: number) => `Fuente ${n}`,
    original: (language: string) => `Original · ${language}`,
    speaker: 'Orador',
    role: 'Cargo',
    group: 'Grupo',
    chamber: 'Cámara',
    date: 'Fecha',
    openRecord: 'Abrir en el registro oficial',
    watch: (start: string, end: string) => `Ver ${start}–${end}`,
    watchNote: 'El tiempo lo marcó una máquina y no lo revisó una persona.',
    close: 'Cerrar',
    howMade: 'Cómo se hizo esta síntesis',
    howRule:
      'La IA lee y escribe. Código simple decide qué cuenta como evidencia y adjunta cada fuente.',
    reviewed: (reviewer: string, date: string | null) =>
      date ? `Revisada por ${reviewer} el ${date}` : `Revisada por ${reviewer}`,
    model: 'Modelo',
    updated: 'Escrita',
    review: 'Revisión humana',
    fullRecord: 'Leer el registro completo',
    prepared: 'Preguntas preparadas',
    preparedNote: 'Respondidas de antemano a partir del registro.',
    preparedPending: 'Esta respuesta todavía se está revisando.',
    own: 'Tu propia pregunta',
    placeholder: 'Preguntá qué se dijo en el Parlamento sobre esto',
    send: 'Preguntar',
    asking: 'Cleisthenes está leyendo el registro…',
    privacy:
      'Tu pregunta se envía sin tu pase y sin tu nombre. No escribas datos personales en ella.',
    noAdvice: 'Cleisthenes explica lo que se dijo. No te dice cómo responder.',
    signIn:
      'Las preguntas propias todavía no están abiertas a todos. Las preguntas preparadas de arriba no necesitan cuenta.',
    spent: 'No quedan preguntas por ahora. Probá más tarde.',
    failed: 'Cleisthenes no pudo responder. Probá de nuevo.',
    unsourced: 'Cleisthenes no encontró ninguna frase que pudiera vincular a una fuente.',
    limits: 'Lo que esta respuesta no cubre',
    limit: {
      'speech-not-decision': 'Informa lo que se dijo, no lo que se decidió.',
      'text-coverage': 'El registro que tenemos no cubre todas las sesiones.',
      'machine-video-timing': 'Los tiempos de video los marcó una máquina.',
      withheld: 'Se retuvieron frases porque ninguna fuente las respaldaba.',
    } as Record<string, string>,
  },
  fr: {
    understand: 'Comprendre',
    ask: 'Demander',
    loading: 'Chargement de la synthèse…',
    unavailable: 'Impossible de charger la synthèse.',
    retry: 'Réessayer',
    none: "Aucune synthèse n'est encore publiée pour cette consultation.",
    officialTitle: 'Titre officiel',
    titleNote: 'Cité mot pour mot. Nous ne le reformulons jamais.',
    decided: 'Ce que le Parlement a décidé',
    nationalCouncil: (date: string | null) =>
      date ? `Conseil national, vote final du ${date}` : 'Conseil national, vote final',
    yes: 'Oui',
    no: 'Non',
    abstained: 'Abstentions',
    passage: 'Le passage',
    meaningYes: 'Un oui signifiait',
    meaningNo: 'Un non signifiait',
    arguments: 'Arguments avancés au Parlement',
    argumentsNote: "Chaque phrase ouvre le passage dont elle vient. L'ordre est toujours le même.",
    forSide: 'Pour',
    againstSide: 'Contre',
    inPreparation: 'Arguments en préparation',
    inPreparationBody:
      'Ils sont publiés après relecture par une personne nommée. Le titre et les chiffres ci-dessus viennent de sources officielles.',
    otherLanguage: (language: string) => `Cette synthèse est disponible en ${language}.`,
    coverThin: (passages: number, speakers: number) =>
      `Le Bulletin officiel couvre peu ce camp : ${passages} ${plural(passages, 'passage', 'passages')} de ${speakers} ${plural(speakers, 'orateur', 'orateurs')}.`,
    coverOne: "Un seul membre s'est exprimé pour ce camp dans le Bulletin officiel.",
    coverSilent:
      'Aucun passage du Bulletin officiel ne défend ce camp. Nous ne comblons pas ce vide.',
    citeLabel: (n: number, speaker: string, date: string | null) =>
      `Source ${n} : ${speaker}${date ? `, ${date}` : ''}. Ouvrir la citation`,
    citation: (n: number) => `Source ${n}`,
    original: (language: string) => `Original · ${language}`,
    speaker: 'Orateur',
    role: 'Fonction',
    group: 'Groupe',
    chamber: 'Conseil',
    date: 'Date',
    openRecord: 'Ouvrir dans le Bulletin officiel',
    watch: (start: string, end: string) => `Vidéo ${start}–${end}`,
    watchNote: "L'alignement est automatique et n'a pas été vérifié par une personne.",
    close: 'Fermer',
    howMade: 'Comment cette synthèse a été faite',
    howRule:
      "L'IA lit et écrit. Du code simple décide de ce qui compte comme preuve et attache chaque source.",
    reviewed: (reviewer: string, date: string | null) =>
      date ? `Relue par ${reviewer} le ${date}` : `Relue par ${reviewer}`,
    model: 'Modèle',
    updated: 'Rédigée',
    review: 'Relecture humaine',
    fullRecord: 'Lire le compte rendu complet',
    prepared: 'Questions préparées',
    preparedNote: "Répondues à l'avance à partir du compte rendu.",
    preparedPending: 'Cette réponse est encore en cours de vérification.',
    own: 'Votre propre question',
    placeholder: 'Demandez ce qui a été dit au Parlement à ce sujet',
    send: 'Demander',
    asking: 'Cleisthenes lit le compte rendu…',
    privacy:
      "Votre question est envoyée sans votre pass et sans votre nom. N'y écrivez pas de données personnelles.",
    noAdvice: 'Cleisthenes explique ce qui a été dit. Il ne vous dit pas comment répondre.',
    signIn:
      'Les questions libres ne sont pas encore ouvertes à tous. Les questions préparées ci-dessus ne demandent aucun compte.',
    spent: "Il ne reste plus de questions pour l'instant. Réessayez plus tard.",
    failed: "Cleisthenes n'a pas pu répondre. Réessayez.",
    unsourced: "Cleisthenes n'a trouvé aucune phrase qu'il pouvait relier à une source.",
    limits: 'Ce que cette réponse ne couvre pas',
    limit: {
      'speech-not-decision': 'Elle rapporte ce qui a été dit, pas ce qui a été décidé.',
      'text-coverage': 'Le compte rendu dont nous disposons ne couvre pas toutes les sessions.',
      'machine-video-timing': 'Les repères vidéo ont été placés par une machine.',
      withheld: 'Des phrases ont été retenues, faute de source pour les appuyer.',
    } as Record<string, string>,
  },
} as const satisfies Record<CicoLocale, unknown>;

export type BriefCopy = (typeof BRIEF_COPY)[CicoLocale];
